name: Run tests

on:
  pull_request:
    branches: [master]


jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install pytest
      run: |
        python3 -m pip install pytest --user
    - name: Install dependencies
      run: |
        python3 -m pip install .
    - name: Test with pytest
      run: |
        pytest --ignore test/test_manm_cs_pypi.py
